import { defineObject, FieldType, RelationType } from 'twenty-sdk/define';

import {
  ASSET_OBJECT_UNIVERSAL_IDENTIFIER,
  ASSET_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  ASSET_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  ASSET_FILE_LINK_FIELD_UNIVERSAL_IDENTIFIER,
  ASSET_TAGS_FIELD_UNIVERSAL_IDENTIFIER,
  ASSET_USAGE_RIGHTS_FIELD_UNIVERSAL_IDENTIFIER,
  ASSET_RELATED_CONTENT_PIECE_FIELD_UNIVERSAL_IDENTIFIER,
  ASSET_RELATED_PROJECT_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  CONTENT_ASSETS_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
  PROJECT_ASSETS_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: ASSET_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'asset',
  namePlural: 'assets',
  labelSingular: 'Asset',
  labelPlural: 'Assets',
  description: 'Media and brand library assets.',
  icon: 'IconPhoto',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    ASSET_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: ASSET_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Name of the asset.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: ASSET_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'assetType',
      label: 'Type',
      description: 'Type of asset.',
      icon: 'IconFile',
      options: [
        { id: '6671c345-79ec-4973-bd8f-a8963468e5db', position: 0, label: 'Image', value: 'IMAGE', color: 'blue' },
        { id: '88707685-b490-4536-9014-ec3bd0153922', position: 1, label: 'Video', value: 'VIDEO', color: 'purple' },
        { id: '3c630b08-6c26-4f67-9cf3-f3be72540f2d', position: 2, label: 'Doc', value: 'DOC', color: 'green' },
        { id: '7cedaaf0-d112-4c62-bf99-5819477e5dfa', position: 3, label: 'Brand Asset', value: 'BRAND_ASSET', color: 'orange' },
      ],
    },
    {
      universalIdentifier: ASSET_FILE_LINK_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'fileLink',
      label: 'File Link',
      description: 'URL or path to the asset file.',
      icon: 'IconLink',
    },
    {
      universalIdentifier: ASSET_TAGS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'tags',
      label: 'Tags',
      description: 'Comma-separated tags for the asset.',
      icon: 'IconTag',
    },
    {
      universalIdentifier: ASSET_USAGE_RIGHTS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'usageRights',
      label: 'Usage Rights',
      description: 'Usage rights information for the asset.',
      icon: 'IconChecklist',
    },
    {
      universalIdentifier: ASSET_RELATED_CONTENT_PIECE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'relatedContentPiece',
      label: 'Related Content Piece',
      description: 'Content piece this asset is used in.',
      icon: 'IconFileText',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: CONTENT_ASSETS_FIELD_UNIVERSAL_IDENTIFIER,
      relationTargetObjectMetadataUniversalIdentifier: CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: 'SET_NULL',
        joinColumnName: 'relatedContentPieceId',
      },
    },
    {
      universalIdentifier: ASSET_RELATED_PROJECT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'relatedProject',
      label: 'Related Project',
      description: 'Project this asset belongs to.',
      icon: 'IconFolder',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: PROJECT_ASSETS_FIELD_UNIVERSAL_IDENTIFIER,
      relationTargetObjectMetadataUniversalIdentifier: PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: 'SET_NULL',
        joinColumnName: 'relatedProjectId',
      },
    },
  ],
});
