import { defineObject, FieldType, RelationType } from 'twenty-sdk/define';

import {
  CAMPAIGN_OBJECT_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_START_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_END_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_GOAL_FIELD_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_CHANNELS_FIELD_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_RELATED_CONTENT_PIECES_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  CONTENT_CAMPAIGN_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: CAMPAIGN_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'campaign',
  namePlural: 'campaigns',
  labelSingular: 'Campaign',
  labelPlural: 'Campaigns',
  description: 'Marketing campaigns managed in the app.',
  icon: 'IconSpeakerphone',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    CAMPAIGN_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: CAMPAIGN_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Name of the campaign.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: CAMPAIGN_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'campaignType',
      label: 'Type',
      description: 'Type of the campaign.',
      icon: 'IconClipboardText',
      defaultValue: `'WEEKLY_CADENCE'`,
      options: [
        { id: 'eb7b9488-5f49-4117-bed8-6952d50c8ed5', position: 0, label: 'Weekly Cadence', value: 'WEEKLY_CADENCE', color: 'blue' },
        { id: '5c91f39a-edaf-4e51-b026-b902d1ebd0b4', position: 1, label: 'Workshop', value: 'WORKSHOP', color: 'purple' },
        { id: 'bf70ef4b-e742-4b3a-9219-6351153a2026', position: 2, label: 'Product Launch', value: 'PRODUCT_LAUNCH', color: 'green' },
        { id: '2122f0af-4772-4672-994f-96ee69303e4b', position: 3, label: 'Funnel', value: 'FUNNEL', color: 'orange' },
      ],
    },
    {
      universalIdentifier: CAMPAIGN_START_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'startDate',
      label: 'Start Date',
      description: 'Campaign start date.',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: CAMPAIGN_END_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'endDate',
      label: 'End Date',
      description: 'Campaign end date.',
      icon: 'IconCalendarEvent',
    },
    {
      universalIdentifier: CAMPAIGN_GOAL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'goal',
      label: 'Goal',
      description: 'Goal of the campaign.',
      icon: 'IconTarget',
    },
    {
      universalIdentifier: CAMPAIGN_CHANNELS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'channels',
      label: 'Channels',
      description: 'Channels used for this campaign.',
      icon: 'IconShare',
    },
    {
      universalIdentifier: CAMPAIGN_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Workflow status of the campaign.',
      icon: 'IconAdjustments',
      defaultValue: `'DRAFT'`,
      options: [
        { id: 'aa5a5b6c-3783-428d-8790-4e41ca41f228', position: 0, label: 'Draft', value: 'DRAFT', color: 'gray' },
        { id: 'd8d44da9-79a4-44d0-b45f-574c6b72b318', position: 1, label: 'Active', value: 'ACTIVE', color: 'green' },
        { id: '2b258a87-7d39-4487-9317-cbe78bc6e67a', position: 2, label: 'Completed', value: 'COMPLETED', color: 'blue' },
        { id: '5a2aa146-bece-4376-90b6-5b83c2e8822b', position: 3, label: 'Paused', value: 'PAUSED', color: 'amber' },
      ],
    },
    {
      universalIdentifier: CAMPAIGN_RELATED_CONTENT_PIECES_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'contentPieces',
      label: 'Content Pieces',
      description: 'Content pieces in this campaign.',
      icon: 'IconFileText',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: CONTENT_CAMPAIGN_FIELD_UNIVERSAL_IDENTIFIER,
      relationTargetObjectMetadataUniversalIdentifier: CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
  ],
});
