import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  CONTENT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  CONTENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'content',
  namePlural: 'contents',
  labelSingular: 'Content',
  labelPlural: 'Contents',
  description: 'Content pieces managed in the app.',
  icon: 'IconFileText',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Name of the content item.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: CONTENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'typeCustom',
      label: 'Type',
      description: 'Content type.',
      icon: 'IconClipboardText',
      options: [
        {
          id: '84b9f8bf-304d-43d5-89a1-8d9cfbfe5f74',
          position: 0,
          label: 'Short-Form',
          value: 'SHORT_FORM',
          color: 'green',
        },
        {
          id: '90bf141c-e336-414c-8c7b-2993e4189a55',
          position: 1,
          label: 'Long-Form',
          value: 'LONG_FORM',
          color: 'amber',
        },
      ],
    },
    {
      universalIdentifier: CONTENT_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.FILES,
      name: 'media',
      label: 'Media',
      description: 'Files attached to this content.',
      icon: 'IconPhoto',
      universalSettings: {
        maxNumberOfValues: 10,
      },
    },
    {
      universalIdentifier: CONTENT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RICH_TEXT,
      name: 'description',
      label: 'Description',
      description: 'Rich text description of the content.',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: CONTENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Workflow status of the content.',
      icon: 'IconAdjustments',
      options: [
        {
          id: '625957ab-f46c-408f-bacc-07e375869c17',
          position: 0,
          label: '01 — Idea / Backlog',
          value: 'OPT01_IDEA_BACKLOG',
          color: 'gray',
        },
        {
          id: 'a8880b19-e469-4f5d-990a-584fd642e580',
          position: 1,
          label: '02 — Approved',
          value: 'OPT02_APPROVED',
          color: 'orange',
        },
        {
          id: '446f3ac5-7a3b-4de6-921a-23456fcb2cb0',
          position: 2,
          label: '03 — Scripting',
          value: 'OPT03_SCRIPTING',
          color: 'pink',
        },
        {
          id: '00a7585a-5344-40e8-a261-6dec62fe83e1',
          position: 3,
          label: '04 — Filming',
          value: 'OPT04_FILMING',
          color: 'purple',
        },
        {
          id: '55b52cf7-2de7-4836-949f-a6aab9c38c21',
          position: 4,
          label: '05 — On Review',
          value: 'OPT05_ON_REVIEW',
          color: 'violet',
        },
        {
          id: '566a0ff1-43dc-4a33-aaad-c1fa3d96ce8a',
          position: 5,
          label: '06 — Publishing Prep',
          value: 'OPT06_PUBLISHING_PREP',
          color: 'amber',
        },
        {
          id: '5100fcb2-4849-496e-8bfa-2f40a67bbd6e',
          position: 6,
          label: '07 — Publishing',
          value: 'OPT07_PUBLISHING',
          color: 'yellow',
        },
        {
          id: '76c13fb7-47eb-438e-82d6-42313d2da1b0',
          position: 7,
          label: '08 — Published',
          value: 'OPT08_PUBLISHED',
          color: 'green',
        },
        {
          id: '1ae9acc2-3256-4b70-9993-d4501b5929a2',
          position: 8,
          label: '09 — Archived',
          value: 'OPT09_ARCHIVED',
          color: 'red',
        },
      ],
    },
  ],
});
