import { defineObject, FieldType, RelationType } from 'twenty-sdk/define';

import {
  CONTENT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  CONTENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_PILLAR_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_PLATFORM_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_CAMPAIGN_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_VIEWS_METRIC_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_LIKES_METRIC_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_HOOK_USED_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_FRAMEWORK_USED_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_CTA_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_ASSETS_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_HANDLES_FIELD_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_OBJECT_UNIVERSAL_IDENTIFIER,
  CAMPAIGN_RELATED_CONTENT_PIECES_FIELD_UNIVERSAL_IDENTIFIER,
  ASSET_OBJECT_UNIVERSAL_IDENTIFIER,
  ASSET_RELATED_CONTENT_PIECE_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'content',
  namePlural: 'contents',
  labelSingular: 'Content',
  labelPlural: 'Contents',
  description: 'Content pieces managed in the app.',
  icon: 'IconFileText',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'topic',
      label: 'Topic',
      description: 'Name of the content item.',
      icon: 'IconAbc',
      defaultValue: `'e.g., How to Build a Personal Brand on LinkedIn'`,
    },
    {
      universalIdentifier: CONTENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'typeCustom',
      label: 'Type',
      description: 'Content type.',
      icon: 'IconClipboardText',
      defaultValue: `'SHORT_FORM'`,
      options: [
        {
          id: '84b9f8bf-304d-43d5-89a1-8d9cfbfe5f74',
          position: 0,
          label: 'Short-Form',
          value: 'SHORT_FORM',
          color: 'green',
        },
        {
          id: '90bf141c-e336-414c-8c7b-2993e4189a55',
          position: 1,
          label: 'Long-Form',
          value: 'LONG_FORM',
          color: 'amber',
        },
      ],
    },
    {
      universalIdentifier: CONTENT_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.FILES,
      name: 'media',
      label: 'Media',
      description: 'Files attached to this content.',
      icon: 'IconPhoto',
      universalSettings: {
        maxNumberOfValues: 10,
      },
    },
    {
      universalIdentifier: CONTENT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RICH_TEXT,
      name: 'description',
      label: 'Description',
      description: 'Rich text description of the content.',
      isNullable: false,
      isUIEditable: true,
      icon: 'IconNotes',
      defaultValue: { blocknote: "'Write your content description here...'", markdown: "'Write your content description here...'" },
    },
    {
      universalIdentifier: CONTENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Workflow status of the content.',
      icon: 'IconAdjustments',
      defaultValue: `'OPT01_IDEA_BACKLOG'`,
      options: [
        {
          id: '625957ab-f46c-408f-bacc-07e375869c17',
          position: 0,
          label: '01 — Idea / Backlog',
          value: 'OPT01_IDEA_BACKLOG',
          color: 'gray',
        },
        {
          id: 'a8880b19-e469-4f5d-990a-584fd642e580',
          position: 1,
          label: '02 — Approved',
          value: 'OPT02_APPROVED',
          color: 'orange',
        },
        {
          id: '446f3ac5-7a3b-4de6-921a-23456fcb2cb0',
          position: 2,
          label: '03 — Scripting',
          value: 'OPT03_SCRIPTING',
          color: 'pink',
        },
        {
          id: '00a7585a-5344-40e8-a261-6dec62fe83e1',
          position: 3,
          label: '04 — Filming',
          value: 'OPT04_FILMING',
          color: 'purple',
        },
        {
          id: '55b52cf7-2de7-4836-949f-a6aab9c38c21',
          position: 4,
          label: '05 — On Review',
          value: 'OPT05_ON_REVIEW',
          color: 'violet',
        },
        {
          id: '566a0ff1-43dc-4a33-aaad-c1fa3d96ce8a',
          position: 5,
          label: '06 — Publishing Prep',
          value: 'OPT06_PUBLISHING_PREP',
          color: 'amber',
        },
        {
          id: '8FE04FA0-71C1-4311-8396-60205B040743',
          position: 6,
          label: '07 — Ready To Publish',
          value: 'OPT07_READY_TO_PUBLISH',
          color: 'green',
        },
        {
          id: '5100fcb2-4849-496e-8bfa-2f40a67bbd6e',
          position: 7,
          label: '08 — Publishing',
          value: 'OPT08_PUBLISHING',
          color: 'yellow',
        },
        {
          id: '76c13fb7-47eb-438e-82d6-42313d2da1b0',
          position: 8,
          label: '09 — Published',
          value: 'OPT09_PUBLISHED',
          color: 'green',
        },
        {
          id: '1ae9acc2-3256-4b70-9993-d4501b5929a2',
          position: 9,
          label: '10 — Archived',
          value: 'OPT10_ARCHIVED',
          color: 'red',
        },
      ],
    },
    {
      universalIdentifier: CONTENT_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'publishAt',
      label: 'Publish At',
      description: 'Date and time when the content should be published.',
      icon: 'IconCalendarEvent',
    },
    {
      universalIdentifier: CONTENT_PILLAR_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'pillar',
      label: 'Pillar',
      description: 'Content pillar (1-5).',
      icon: 'IconStack',
      defaultValue: `'PILLAR_1'`,
      options: [
        { id: 'b7c84a76-221f-4883-8d57-819c5d2e05a6', position: 0, label: 'Pillar 1', value: 'PILLAR_1', color: 'blue' },
        { id: 'e7409575-aef3-463a-bdc5-04e474e6eb55', position: 1, label: 'Pillar 2', value: 'PILLAR_2', color: 'purple' },
        { id: 'b7c87e64-afd0-4c94-8dc8-1fd10b4e4bb1', position: 2, label: 'Pillar 3', value: 'PILLAR_3', color: 'green' },
        { id: 'b3dc8a74-1f17-4c24-bc77-ab696f0cafb5', position: 3, label: 'Pillar 4', value: 'PILLAR_4', color: 'orange' },
        { id: '7a06d107-6194-47b2-ae7a-7a755388da04', position: 4, label: 'Pillar 5', value: 'PILLAR_5', color: 'pink' },
      ],
    },
    {
      universalIdentifier: CONTENT_PLATFORM_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'platform',
      label: 'Platform',
      description: 'Target platform.',
      icon: 'IconShare',
      defaultValue: `'LINKEDIN'`,
      options: [
        { id: '5b6943e6-8736-4025-b92a-41b40e32db88', position: 0, label: 'LinkedIn', value: 'LINKEDIN', color: 'blue' },
        { id: '12ad1725-8258-47d7-b3e7-ee6ad046c5ac', position: 1, label: 'Instagram', value: 'INSTAGRAM', color: 'purple' },
        { id: '58471e47-b63f-4020-95e6-5e97d37840d2', position: 2, label: 'TikTok', value: 'TIKTOK', color: 'pink' },
        { id: 'a0ba63a2-0d7a-446e-be5f-ce2212fd7b31', position: 3, label: 'YouTube', value: 'YOUTUBE', color: 'red' },
        { id: '5689a736-108f-4b6b-85e2-9a668c6bebdb', position: 4, label: 'Reddit', value: 'REDDIT', color: 'orange' },
        { id: '1506b284-73e3-4582-8f23-ce1154440a77', position: 5, label: 'X', value: 'X', color: 'gray' },
        { id: 'e554c18f-b4f7-42ec-b9e9-d36172dd88c1', position: 6, label: 'Telegram', value: 'TELEGRAM', color: 'blue' },
        { id: '564efe68-7897-43af-a66c-a72095f1e012', position: 7, label: 'Threads', value: 'THREADS', color: 'violet' },
        { id: '0da8a236-7c48-430c-b5cf-95c399bbb6d4', position: 8, label: 'DS — CS', value: 'DS_CS', color: 'orange' },
        { id: '5cf06a16-0ba2-4bd5-8b4e-308a4bc32147', position: 9, label: 'Medium', value: 'MEDIUM', color: 'green' },
        { id: 'd9333cc1-7fab-4b85-9456-9ca1e762506c', position: 10, label: 'Substack', value: 'SUBSTACK', color: 'orange' },
        { id: '8746534e-9dc7-48f8-b7d3-556616a24319', position: 11, label: 'LinkedIn Article', value: 'LINKEDIN_ARTICLE', color: 'blue' },
      ],
    },
    {
      universalIdentifier: CONTENT_CAMPAIGN_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'campaign',
      label: 'Campaign',
      description: 'The campaign this content belongs to.',
      icon: 'IconSpeakerphone',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: CAMPAIGN_RELATED_CONTENT_PIECES_FIELD_UNIVERSAL_IDENTIFIER,
      relationTargetObjectMetadataUniversalIdentifier: CAMPAIGN_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: 'SET_NULL',
        joinColumnName: 'campaignId',
      },
    },
    {
      universalIdentifier: CONTENT_VIEWS_METRIC_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'viewsMetric',
      label: 'Views',
      description: 'Number of views.',
      icon: 'IconEye',
      defaultValue: 0,
    },
    {
      universalIdentifier: CONTENT_LIKES_METRIC_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'likesMetric',
      label: 'Likes',
      description: 'Number of likes.',
      icon: 'IconHeart',
      defaultValue: 0,
    },
    {
      universalIdentifier: CONTENT_HOOK_USED_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'hookUsed',
      label: 'Hook Used',
      description: 'Text reference to hook used.',
      icon: 'IconHook',
      defaultValue: `'e.g., Question Hook, Statistic Hook, Bold Statement'`,
    },
    {
      universalIdentifier: CONTENT_FRAMEWORK_USED_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'frameworkUsed',
      label: 'Framework Used',
      description: 'Text reference to framework used.',
      icon: 'IconLayoutGrid',
      defaultValue: `'e.g., AIDA, PAS, Before-After-Bridge'`,
    },
    {
      universalIdentifier: CONTENT_CTA_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'ctaType',
      label: 'CTA Type',
      description: 'Call to action type.',
      icon: 'IconMouse',
      defaultValue: `'SCORECARD'`,
      options: [
        { id: 'def5af39-b1f1-49d5-b494-937f3b2d8887', position: 0, label: 'Scorecard', value: 'SCORECARD', color: 'blue' },
        { id: '078ae630-1ad8-4651-aeef-ae2acd3b46c8', position: 1, label: 'Guide', value: 'GUIDE', color: 'green' },
        { id: '1b462326-3392-4bee-b896-4c20aa967546', position: 2, label: 'Workshop', value: 'WORKSHOP', color: 'purple' },
      ],
    },
    {
      universalIdentifier: CONTENT_HANDLES_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'handles',
      label: 'Handles',
      description: 'Social media handles per platform (e.g. @john on IG, @john_dev on X).',
      icon: 'IconAt',
      defaultValue: `'@username_ig, @username_x, @username_yt'`,
    },
    {
      universalIdentifier: CONTENT_ASSETS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'assets',
      label: 'Assets',
      description: 'Media assets linked to this content.',
      icon: 'IconPhoto',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: ASSET_RELATED_CONTENT_PIECE_FIELD_UNIVERSAL_IDENTIFIER,
      relationTargetObjectMetadataUniversalIdentifier: ASSET_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
  ],
});
