import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  FUNNEL_LEAD_OBJECT_UNIVERSAL_IDENTIFIER,
  FUNNEL_LEAD_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  FUNNEL_LEAD_EMAIL_FIELD_UNIVERSAL_IDENTIFIER,
  FUNNEL_LEAD_PHONE_FIELD_UNIVERSAL_IDENTIFIER,
  FUNNEL_LEAD_SOURCE_FIELD_UNIVERSAL_IDENTIFIER,
  FUNNEL_LEAD_SCORECARD_TIER_FIELD_UNIVERSAL_IDENTIFIER,
  FUNNEL_LEAD_QUALIFICATION_ANSWERS_FIELD_UNIVERSAL_IDENTIFIER,
  FUNNEL_LEAD_RELATED_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
  FUNNEL_LEAD_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: FUNNEL_LEAD_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'funnelLead',
  namePlural: 'funnelLeads',
  labelSingular: 'Funnel Lead',
  labelPlural: 'Funnel Leads',
  description: 'Funnel leads managed in the app.',
  icon: 'IconFunnel',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    FUNNEL_LEAD_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: FUNNEL_LEAD_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Name of the funnel lead.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: FUNNEL_LEAD_EMAIL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'email',
      label: 'Email',
      description: 'Email of the funnel lead.',
      icon: 'IconMail',
    },
    {
      universalIdentifier: FUNNEL_LEAD_PHONE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'phone',
      label: 'Phone',
      description: 'Phone number of the funnel lead.',
      icon: 'IconPhone',
    },
    {
      universalIdentifier: FUNNEL_LEAD_SOURCE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'source',
      label: 'Source',
      description: 'Source of the funnel lead.',
      icon: 'IconSource',
      defaultValue: `'MAGNET'`,
      options: [
        { id: '4a2eb595-9386-4334-9657-472f2d92149b', position: 0, label: 'Magnet', value: 'MAGNET', color: 'blue' },
        { id: '51994fd4-c382-4bf3-a585-6aa584fbdf85', position: 1, label: 'Quiz', value: 'QUIZ', color: 'purple' },
        { id: 'babbfaab-464a-42b3-a5a6-4fa9ca6f398d', position: 2, label: 'Workshop', value: 'WORKSHOP', color: 'green' },
        { id: 'c6c6b273-b95e-4618-80d9-d6425c37abb8', position: 3, label: 'Waitlist', value: 'WAITLIST', color: 'orange' },
      ],
    },
    {
      universalIdentifier: FUNNEL_LEAD_SCORECARD_TIER_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'scorecardTier',
      label: 'Scorecard Tier',
      description: 'Scorecard tier of the funnel lead.',
      icon: 'IconChartBar',
      options: [
        { id: '88b746b6-cc30-48a3-a240-d998e66d454a', position: 0, label: 'Flatlining', value: 'FLATLINING', color: 'red' },
        { id: 'd9e70dca-23d9-4df0-959a-58863556e776', position: 1, label: 'Unstable', value: 'UNSTABLE', color: 'orange' },
        { id: '526db70c-0294-4e9a-a42e-14774919eab5', position: 2, label: 'Stabilizing', value: 'STABILIZING', color: 'amber' },
        { id: 'e0f94de5-d5b0-41cf-91f0-554a5dd4d8d2', position: 3, label: 'Compounding', value: 'COMPOUNDING', color: 'green' },
      ],
    },
    {
      universalIdentifier: FUNNEL_LEAD_QUALIFICATION_ANSWERS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'qualificationAnswers',
      label: 'Qualification Answers',
      description: 'Qualification answers of the funnel lead.',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: FUNNEL_LEAD_RELATED_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'relatedOpportunity',
      label: 'Related Opportunity',
      description: 'Related opportunity for this funnel lead.',
      icon: 'IconTarget',
    },
    {
      universalIdentifier: FUNNEL_LEAD_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Workflow status of the funnel lead.',
      icon: 'IconAdjustments',
      defaultValue: `'NEW'`,
      options: [
        { id: '79c986b2-5a69-46e9-b486-7c3aeee5e6c5', position: 0, label: 'New', value: 'NEW', color: 'blue' },
        { id: 'aaac894e-8519-4da5-972b-b5ec63d8b4c7', position: 1, label: 'Contacted', value: 'CONTACTED', color: 'amber' },
        { id: 'cc465cfd-25b5-4b0a-84f3-75ce10e63892', position: 2, label: 'Converted', value: 'CONVERTED', color: 'green' },
        { id: '8a4d651f-9a49-4cf0-b0ae-1380981afba9', position: 3, label: 'Dead', value: 'DEAD', color: 'red' },
      ],
    },
  ],
});
