import { defineObject, FieldType, RelationType } from 'twenty-sdk/define';

import {
  PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
  PROJECT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_OWNER_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_START_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_TARGET_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_RELATED_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_RELATED_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_ASSETS_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_PRODUCT_FIELD_UNIVERSAL_IDENTIFIER,
  PROJECT_ROLE_FIELD_UNIVERSAL_IDENTIFIER,
  ASSET_OBJECT_UNIVERSAL_IDENTIFIER,
  ASSET_RELATED_PROJECT_FIELD_UNIVERSAL_IDENTIFIER,
  PRODUCT_OBJECT_UNIVERSAL_IDENTIFIER,
  PRODUCT_PROJECTS_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'project',
  namePlural: 'projects',
  labelSingular: 'Project',
  labelPlural: 'Projects',
  description: 'Projects managed in the app.',
  icon: 'IconFolder',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    PROJECT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: PROJECT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Name of the project.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: PROJECT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'projectType',
      label: 'Project Type',
      description: 'Type of the project.',
      icon: 'IconTag',
      defaultValue: `'CLIENT_DELIVERY'`,
      options: [
        { id: '16841a4f-40e9-4999-8807-8a2517b54801', position: 0, label: 'Client Delivery', value: 'CLIENT_DELIVERY', color: 'blue' },
        { id: 'a74b0f92-4fce-4eed-b990-9a69c0e83b4c', position: 1, label: 'DS Product Build', value: 'DS_PRODUCT_BUILD', color: 'purple' },
        { id: '5eab07c0-b238-494d-8332-f905f3549127', position: 2, label: 'DS Marketing', value: 'DS_MARKETING', color: 'green' },
        { id: '75c99d8b-5b65-41ef-a372-12623db3a536', position: 3, label: 'Personal Brand', value: 'PERSONAL_BRAND', color: 'orange' },
        { id: '81df6b54-5176-40b8-9ab5-7b55b1b33796', position: 4, label: 'Internal Ops', value: 'INTERNAL_OPS', color: 'gray' },
      ],
    },
    {
      universalIdentifier: PROJECT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Workflow status of the project.',
      icon: 'IconAdjustments',
      defaultValue: `'ACTIVE'`,
      options: [
        { id: 'fc5f6e06-92b1-437a-ae1c-7742b1da00d1', position: 0, label: 'Planning', value: 'PLANNING', color: 'gray' },
        { id: '62929fb0-a4b2-4278-8ac9-74a674d340bb', position: 1, label: 'Active', value: 'ACTIVE', color: 'green' },
        { id: 'ad0af53f-772b-4c6e-8597-6c52a3b85f55', position: 2, label: 'On Hold', value: 'ON_HOLD', color: 'amber' },
        { id: '5c75f2c7-a4ab-4558-90ec-3d3913183737', position: 3, label: 'Completed', value: 'COMPLETED', color: 'blue' },
        { id: '638b7f41-8e83-41d9-bdfb-c6f8255a3386', position: 4, label: 'Archived', value: 'ARCHIVED', color: 'red' },
      ],
    },
    {
      universalIdentifier: PROJECT_OWNER_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'owner',
      label: 'Owner',
      description: 'Owner of the project.',
      icon: 'IconUser',
    },
    {
      universalIdentifier: PROJECT_ROLE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'roleCustom',
      label: 'Role',
      description: 'Role responsible for this project.',
      icon: 'IconBriefcase',
      options: [
        { id: '42810c2e-c216-4851-8401-13c53da6ecc5', position: 0, label: 'Manager', value: 'MANAGER', color: 'blue' },
        { id: 'cb10c183-fbaf-4086-88c9-3483dc869b5f', position: 1, label: 'Founder', value: 'FOUNDER', color: 'purple' },
        { id: 'f9893ca2-ba04-463e-8094-579e9415dfeb', position: 2, label: 'Editor', value: 'EDITOR', color: 'green' },
        { id: '5ebbb369-bb7f-49be-b3a6-0b0220f4836e', position: 3, label: 'Script Writer', value: 'SCRIPT_WRITER', color: 'orange' },
        { id: '16b455c0-faad-40e5-af81-fa94349714f1', position: 4, label: 'Account Manager', value: 'ACCOUNT_MANAGER', color: 'yellow' },
        { id: '43a7fde4-19fb-4017-9703-23af473fc490', position: 5, label: 'Designer', value: 'DESIGNER', color: 'pink' },
        { id: 'dc5cfb99-dd34-4545-b42d-53064c809ab4', position: 6, label: 'Videographer', value: 'VIDEOGRAPHER', color: 'cyan' },
        { id: 'cfa9ff27-ffd4-4b6e-ae30-7bbee1b167a3', position: 7, label: 'Copywriter', value: 'COPYWRITER', color: 'teal' },
        { id: 'e2d20d3d-2c1c-4b61-be4f-5aef3a34361b', position: 8, label: 'Social Media Manager', value: 'SOCIAL_MEDIA_MANAGER', color: 'red' },
        { id: '2a384ce0-65e6-4be8-8d50-9f47309203e4', position: 9, label: 'Marketing Lead', value: 'MARKETING_LEAD', color: 'violet' },
      ],
    },
    {
      universalIdentifier: PROJECT_START_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'startDate',
      label: 'Start Date',
      description: 'Project start date.',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: PROJECT_TARGET_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'targetDate',
      label: 'Target Date',
      description: 'Project target completion date.',
      icon: 'IconCalendarEvent',
    },
    {
      universalIdentifier: PROJECT_RELATED_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'relatedCompany',
      label: 'Related Company',
      description: 'Related company for this project.',
      icon: 'IconBuilding',
    },
    {
      universalIdentifier: PROJECT_RELATED_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'relatedOpportunity',
      label: 'Related Opportunity',
      description: 'Related opportunity for this project.',
      icon: 'IconTarget',
    },
    {
      universalIdentifier: PROJECT_ASSETS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'assets',
      label: 'Assets',
      description: 'Media assets linked to this project.',
      icon: 'IconPhoto',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: ASSET_RELATED_PROJECT_FIELD_UNIVERSAL_IDENTIFIER,
      relationTargetObjectMetadataUniversalIdentifier: ASSET_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    {
      universalIdentifier: PROJECT_PRODUCT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'product',
      label: 'Product',
      description: 'Product associated with this project.',
      icon: 'IconPackage',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: PRODUCT_PROJECTS_FIELD_UNIVERSAL_IDENTIFIER,
      relationTargetObjectMetadataUniversalIdentifier: PRODUCT_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: 'SET_NULL',
        joinColumnName: 'productId',
      },
    },
  ],
});
