import { defineView, ViewType } from 'twenty-sdk/define';

import {
  CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_IDEA_BACKLOG_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_APPROVED_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_SCRIPTING_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_FILMING_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_ON_REVIEW_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_PUBLISHING_PREP_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_PUBLISHING_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_PUBLISHED_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_ARCHIVED_UNIVERSAL_IDENTIFIER,
  STATUS_VIEW_GROUP_READY_TO_PUBLISH_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineView({
  universalIdentifier: STATUS_VIEW_UNIVERSAL_IDENTIFIER,
  name: 'Status View',
  objectUniversalIdentifier: CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  icon: 'IconKanban',
  type: ViewType.KANBAN,
  position: 0,
  mainGroupByFieldMetadataUniversalIdentifier: CONTENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: STATUS_VIEW_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier: CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      position: 0,
      isVisible: true,
    },
    {
      universalIdentifier: STATUS_VIEW_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier: CONTENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      position: 1,
      isVisible: true,
    },
    {
      universalIdentifier: STATUS_VIEW_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier: CONTENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      position: 2,
      isVisible: true,
    },
    {
      universalIdentifier: STATUS_VIEW_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier: CONTENT_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
      position: 3,
      isVisible: true,
    },
    {
      universalIdentifier: STATUS_VIEW_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier: CONTENT_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
      position: 4,
      isVisible: true,
    },
    {
      universalIdentifier: STATUS_VIEW_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier: CONTENT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
      position: 5,
      isVisible: true,
    },
  ],
  groups: [
    {
      universalIdentifier: STATUS_VIEW_GROUP_IDEA_BACKLOG_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT01_IDEA_BACKLOG',
      isVisible: true,
      position: 0,
    },
    {
      universalIdentifier: STATUS_VIEW_GROUP_APPROVED_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT02_APPROVED',
      isVisible: true,
      position: 1,
    },
    {
      universalIdentifier: STATUS_VIEW_GROUP_SCRIPTING_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT03_SCRIPTING',
      isVisible: true,
      position: 2,
    },
    {
      universalIdentifier: STATUS_VIEW_GROUP_FILMING_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT04_FILMING',
      isVisible: true,
      position: 3,
    },
    {
      universalIdentifier: STATUS_VIEW_GROUP_ON_REVIEW_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT05_ON_REVIEW',
      isVisible: true,
      position: 4,
    },
    {
      universalIdentifier: STATUS_VIEW_GROUP_PUBLISHING_PREP_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT06_PUBLISHING_PREP',
      isVisible: true,
      position: 5,
    },
    {
      universalIdentifier: STATUS_VIEW_GROUP_READY_TO_PUBLISH_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT07_READY_TO_PUBLISH',
      isVisible: true,
      position: 6,
    },
    {
      universalIdentifier: STATUS_VIEW_GROUP_PUBLISHING_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT08_PUBLISHING',
      isVisible: true,
      position: 7,
    },
    {
      universalIdentifier: STATUS_VIEW_GROUP_PUBLISHED_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT09_PUBLISHED',
      isVisible: true,
      position: 8,
    },
    {
      universalIdentifier: STATUS_VIEW_GROUP_ARCHIVED_UNIVERSAL_IDENTIFIER,
      fieldValue: 'OPT10_ARCHIVED',
      isVisible: true,
      position: 9,
    },
  ],
});
