import { defineView, ViewType } from 'twenty-sdk/define';

import {
  CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_PLATFORM_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_PILLAR_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_CAMPAIGN_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_VIEWS_METRIC_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_LIKES_METRIC_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_HOOK_USED_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_FRAMEWORK_USED_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_CTA_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  CONTENT_HANDLES_FIELD_UNIVERSAL_IDENTIFIER,
  TABLE_VIEW_UNIVERSAL_IDENTIFIER,
  TABLE_VIEW_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineView({
  universalIdentifier: TABLE_VIEW_UNIVERSAL_IDENTIFIER,
  name: 'Table View',
  objectUniversalIdentifier: CONTENT_OBJECT_UNIVERSAL_IDENTIFIER,
  type: ViewType.TABLE,
  icon: 'IconList',
  position: 1,
  fields: [
    {
      universalIdentifier: '2db9aadb-453c-4c46-8ab9-4d0c0b4fdef9',
      fieldMetadataUniversalIdentifier: CONTENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      position: 0,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: '2cb4e8b6-537d-4353-b304-a0a598892e29',
      fieldMetadataUniversalIdentifier: CONTENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      position: 1,
      isVisible: true,
      size: 120,
    },
    {
      universalIdentifier: '29d0f4f9-b7bc-47cb-bdce-0a6120280d40',
      fieldMetadataUniversalIdentifier: CONTENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      position: 2,
      isVisible: true,
      size: 150,
    },
    {
      universalIdentifier: '289acede-6dde-4b24-9f0e-289578014687',
      fieldMetadataUniversalIdentifier: CONTENT_PLATFORM_FIELD_UNIVERSAL_IDENTIFIER,
      position: 3,
      isVisible: true,
      size: 120,
    },
    {
      universalIdentifier: '11b48a83-6f81-48f7-8639-ba4bc751046d',
      fieldMetadataUniversalIdentifier: CONTENT_PILLAR_FIELD_UNIVERSAL_IDENTIFIER,
      position: 4,
      isVisible: true,
      size: 120,
    },
    {
      universalIdentifier: TABLE_VIEW_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier: CONTENT_PUBLISH_AT_FIELD_UNIVERSAL_IDENTIFIER,
      position: 5,
      isVisible: true,
      size: 160,
    },
    {
      universalIdentifier: 'c9e02d38-5b60-4138-bec4-e1715ce139a3',
      fieldMetadataUniversalIdentifier: CONTENT_CAMPAIGN_FIELD_UNIVERSAL_IDENTIFIER,
      position: 6,
      isVisible: true,
      size: 150,
    },
    {
      universalIdentifier: '591d0565-9018-48ac-a51c-e1e91615d7c0',
      fieldMetadataUniversalIdentifier: CONTENT_VIEWS_METRIC_FIELD_UNIVERSAL_IDENTIFIER,
      position: 7,
      isVisible: true,
      size: 100,
    },
    {
      universalIdentifier: 'a7acbfb7-2cae-49fb-a6ff-346d207b74fc',
      fieldMetadataUniversalIdentifier: CONTENT_LIKES_METRIC_FIELD_UNIVERSAL_IDENTIFIER,
      position: 8,
      isVisible: true,
      size: 100,
    },
    {
      universalIdentifier: 'bf744ca0-bb66-41a7-8db7-379423b35bd5',
      fieldMetadataUniversalIdentifier: CONTENT_HOOK_USED_FIELD_UNIVERSAL_IDENTIFIER,
      position: 9,
      isVisible: true,
      size: 140,
    },
    {
      universalIdentifier: '45ff080c-7ae4-45a2-ac4b-e6d8d6cb5fc0',
      fieldMetadataUniversalIdentifier: CONTENT_FRAMEWORK_USED_FIELD_UNIVERSAL_IDENTIFIER,
      position: 10,
      isVisible: true,
      size: 140,
    },
    {
      universalIdentifier: '2a384ce0-65e6-4be8-8d50-9f47309203e4',
      fieldMetadataUniversalIdentifier: CONTENT_CTA_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      position: 11,
      isVisible: true,
      size: 120,
    },
    {
      universalIdentifier: 'f98414d6-2cfc-4b06-89db-fef0ebd4f988',
      fieldMetadataUniversalIdentifier: CONTENT_MEDIA_FIELD_UNIVERSAL_IDENTIFIER,
      position: 12,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: '7f4b3eec-4927-4a96-a409-e4a690ebe881',
      fieldMetadataUniversalIdentifier: CONTENT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
      position: 13,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: '303c4cbb-69e2-4ce3-a81a-1b56859e499a',
      fieldMetadataUniversalIdentifier: CONTENT_HANDLES_FIELD_UNIVERSAL_IDENTIFIER,
      position: 14,
      isVisible: true,
      size: 200,
    },
  ],
});
